# Markdownlint configuration for Claude Code Command System
# Aligned with project documentation standards

# Files to ignore are specified in .markdownlintignore

# Default state for all rules
default: true

# Customize specific rules
MD001: false # Header levels should only increment by one level at a time
MD003: # Header style
  style: "atx"
MD007: # Unordered list indentation
  indent: 2
MD010: # Hard tabs
  code_blocks: false
MD013: false # Line length - disabled
MD022: # Headers should be surrounded by blank lines
  lines_above: 1
  lines_below: 1
MD024: false # Multiple headers with the same content
MD025: false # Multiple top level headers in the same document
MD026: # Trailing punctuation in header
  punctuation: ".,;:!?"
MD029: # Ordered list item prefix
  style: "one_or_ordered"
MD033: # Allow inline HTML
  allowed_elements: ["br", "sub", "sup", "kbd", "details", "summary"]
MD036: false # Emphasis used instead of a header
MD041: false # First line in file should be a top level header (conflicts with YAML frontmatter)
MD040: # Fenced code blocks should have a language specified
  allowed_languages:
    [
      "bash",
      "sh",
      "shell",
      "python",
      "py",
      "yaml",
      "yml",
      "json",
      "javascript",
      "js",
      "jsx",
      "typescript",
      "ts",
      "tsx",
      "sql",
      "markdown",
      "md",
      "text",
      "mermaid",
      "powershell",
      "graphql",
      "diff",
      "plaintext",
      "html",
      "css",
    ]
  language_only: false
MD046: # Code block style
  style: "fenced"
MD049: # Emphasis style
  style: "asterisk"
MD050: # Strong style
  style: "asterisk"
MD051: false # Link fragments - disabled due to emoji heading issues
